# Generated by Django 4.2.5 on 2023-10-20 03:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_rename_caption_pollspagechoice_choice_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollspage",
            options={"verbose_name": "投票する"},
        ),
    ]
