# Generated by Django 4.2.5 on 2023-10-23 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_alter_pollspage_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
