# Generated by Django 4.2.5 on 2023-11-07 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_delete_choice_delete_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollspage",
            options={},
        ),
    ]
