# Generated by Django 4.2.5 on 2023-11-07 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_alter_pollspage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollspage",
            options={"verbose_name": "質問の追加"},
        ),
    ]
