# Generated by Django 4.2.5 on 2023-11-10 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_polls_alter_pollspagechoice_choice_text_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollspage",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="pollspage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="pollspagechoice",
            name="question",
        ),
        migrations.DeleteModel(
            name="PollsIndexPage",
        ),
        migrations.DeleteModel(
            name="PollsPage",
        ),
        migrations.DeleteModel(
            name="PollsPageChoice",
        ),
    ]
